// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.Contexts;

#nullable disable

namespace Kazka.Persistence.Migrations
{
    [DbContext(typeof(KazkaContext))]
    [Migration("20251101000203_Migration3")]
    partial class Migration3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Audio", b =>
                {
                    b.Property<long>("ChapterId")
                        .HasColumnType("bigint");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(2083)
                        .HasColumnType("character varying(2083)");

                    b.HasKey("ChapterId");

                    b.ToTable("audios", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Domain.Entities.Chapter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BookId")
                        .HasColumnType("bigint");

                    b.Property<short>("Order")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("chapters", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Language", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Code");

                    b.ToTable("languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "aa"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "af"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "agq"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "ak"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "am"
                        },
                        new
                        {
                            Id = 6L,
                            Code = "ar"
                        },
                        new
                        {
                            Id = 7L,
                            Code = "arn"
                        },
                        new
                        {
                            Id = 8L,
                            Code = "as"
                        },
                        new
                        {
                            Id = 9L,
                            Code = "asa"
                        },
                        new
                        {
                            Id = 10L,
                            Code = "ast"
                        },
                        new
                        {
                            Id = 11L,
                            Code = "az"
                        },
                        new
                        {
                            Id = 14L,
                            Code = "ba"
                        },
                        new
                        {
                            Id = 15L,
                            Code = "bas"
                        },
                        new
                        {
                            Id = 16L,
                            Code = "be"
                        },
                        new
                        {
                            Id = 17L,
                            Code = "bem"
                        },
                        new
                        {
                            Id = 18L,
                            Code = "bez"
                        },
                        new
                        {
                            Id = 19L,
                            Code = "bg"
                        },
                        new
                        {
                            Id = 20L,
                            Code = "bm"
                        },
                        new
                        {
                            Id = 21L,
                            Code = "bn"
                        },
                        new
                        {
                            Id = 22L,
                            Code = "bo"
                        },
                        new
                        {
                            Id = 23L,
                            Code = "br"
                        },
                        new
                        {
                            Id = 24L,
                            Code = "brx"
                        },
                        new
                        {
                            Id = 25L,
                            Code = "bs"
                        },
                        new
                        {
                            Id = 28L,
                            Code = "byn"
                        },
                        new
                        {
                            Id = 29L,
                            Code = "ca"
                        },
                        new
                        {
                            Id = 30L,
                            Code = "ccp"
                        },
                        new
                        {
                            Id = 31L,
                            Code = "ce"
                        },
                        new
                        {
                            Id = 32L,
                            Code = "ceb"
                        },
                        new
                        {
                            Id = 33L,
                            Code = "cgg"
                        },
                        new
                        {
                            Id = 34L,
                            Code = "chr"
                        },
                        new
                        {
                            Id = 35L,
                            Code = "ckb"
                        },
                        new
                        {
                            Id = 36L,
                            Code = "co"
                        },
                        new
                        {
                            Id = 37L,
                            Code = "cs"
                        },
                        new
                        {
                            Id = 38L,
                            Code = "cu"
                        },
                        new
                        {
                            Id = 39L,
                            Code = "cy"
                        },
                        new
                        {
                            Id = 40L,
                            Code = "da"
                        },
                        new
                        {
                            Id = 41L,
                            Code = "dav"
                        },
                        new
                        {
                            Id = 42L,
                            Code = "de"
                        },
                        new
                        {
                            Id = 43L,
                            Code = "dje"
                        },
                        new
                        {
                            Id = 44L,
                            Code = "dsb"
                        },
                        new
                        {
                            Id = 45L,
                            Code = "dua"
                        },
                        new
                        {
                            Id = 46L,
                            Code = "dv"
                        },
                        new
                        {
                            Id = 47L,
                            Code = "dyo"
                        },
                        new
                        {
                            Id = 48L,
                            Code = "dz"
                        },
                        new
                        {
                            Id = 49L,
                            Code = "ebu"
                        },
                        new
                        {
                            Id = 50L,
                            Code = "ee"
                        },
                        new
                        {
                            Id = 51L,
                            Code = "el"
                        },
                        new
                        {
                            Id = 52L,
                            Code = "en"
                        },
                        new
                        {
                            Id = 53L,
                            Code = "eo"
                        },
                        new
                        {
                            Id = 54L,
                            Code = "es"
                        },
                        new
                        {
                            Id = 55L,
                            Code = "et"
                        },
                        new
                        {
                            Id = 56L,
                            Code = "eu"
                        },
                        new
                        {
                            Id = 57L,
                            Code = "ewo"
                        },
                        new
                        {
                            Id = 58L,
                            Code = "fa"
                        },
                        new
                        {
                            Id = 59L,
                            Code = "ff"
                        },
                        new
                        {
                            Id = 61L,
                            Code = "fi"
                        },
                        new
                        {
                            Id = 62L,
                            Code = "fil"
                        },
                        new
                        {
                            Id = 63L,
                            Code = "fo"
                        },
                        new
                        {
                            Id = 64L,
                            Code = "fr"
                        },
                        new
                        {
                            Id = 65L,
                            Code = "fur"
                        },
                        new
                        {
                            Id = 66L,
                            Code = "fy"
                        },
                        new
                        {
                            Id = 67L,
                            Code = "ga"
                        },
                        new
                        {
                            Id = 68L,
                            Code = "gd"
                        },
                        new
                        {
                            Id = 69L,
                            Code = "gl"
                        },
                        new
                        {
                            Id = 70L,
                            Code = "gn"
                        },
                        new
                        {
                            Id = 71L,
                            Code = "gsw"
                        },
                        new
                        {
                            Id = 72L,
                            Code = "gu"
                        },
                        new
                        {
                            Id = 73L,
                            Code = "guz"
                        },
                        new
                        {
                            Id = 74L,
                            Code = "gv"
                        },
                        new
                        {
                            Id = 75L,
                            Code = "ha"
                        },
                        new
                        {
                            Id = 76L,
                            Code = "haw"
                        },
                        new
                        {
                            Id = 77L,
                            Code = "he"
                        },
                        new
                        {
                            Id = 78L,
                            Code = "hi"
                        },
                        new
                        {
                            Id = 79L,
                            Code = "hr"
                        },
                        new
                        {
                            Id = 80L,
                            Code = "hsb"
                        },
                        new
                        {
                            Id = 81L,
                            Code = "hu"
                        },
                        new
                        {
                            Id = 82L,
                            Code = "hy"
                        },
                        new
                        {
                            Id = 83L,
                            Code = "ia"
                        },
                        new
                        {
                            Id = 84L,
                            Code = "id"
                        },
                        new
                        {
                            Id = 85L,
                            Code = "ig"
                        },
                        new
                        {
                            Id = 86L,
                            Code = "ii"
                        },
                        new
                        {
                            Id = 87L,
                            Code = "is"
                        },
                        new
                        {
                            Id = 88L,
                            Code = "it"
                        },
                        new
                        {
                            Id = 89L,
                            Code = "iu"
                        },
                        new
                        {
                            Id = 91L,
                            Code = "ja"
                        },
                        new
                        {
                            Id = 92L,
                            Code = "jgo"
                        },
                        new
                        {
                            Id = 93L,
                            Code = "jmc"
                        },
                        new
                        {
                            Id = 94L,
                            Code = "jv"
                        },
                        new
                        {
                            Id = 95L,
                            Code = "ka"
                        },
                        new
                        {
                            Id = 96L,
                            Code = "kab"
                        },
                        new
                        {
                            Id = 97L,
                            Code = "kam"
                        },
                        new
                        {
                            Id = 98L,
                            Code = "kde"
                        },
                        new
                        {
                            Id = 99L,
                            Code = "kea"
                        },
                        new
                        {
                            Id = 100L,
                            Code = "khq"
                        },
                        new
                        {
                            Id = 101L,
                            Code = "ki"
                        },
                        new
                        {
                            Id = 102L,
                            Code = "kk"
                        },
                        new
                        {
                            Id = 103L,
                            Code = "kkj"
                        },
                        new
                        {
                            Id = 104L,
                            Code = "kl"
                        },
                        new
                        {
                            Id = 105L,
                            Code = "kln"
                        },
                        new
                        {
                            Id = 106L,
                            Code = "km"
                        },
                        new
                        {
                            Id = 107L,
                            Code = "kn"
                        },
                        new
                        {
                            Id = 108L,
                            Code = "ko"
                        },
                        new
                        {
                            Id = 109L,
                            Code = "kok"
                        },
                        new
                        {
                            Id = 110L,
                            Code = "ks"
                        },
                        new
                        {
                            Id = 111L,
                            Code = "ksb"
                        },
                        new
                        {
                            Id = 112L,
                            Code = "ksf"
                        },
                        new
                        {
                            Id = 113L,
                            Code = "ksh"
                        },
                        new
                        {
                            Id = 114L,
                            Code = "kw"
                        },
                        new
                        {
                            Id = 115L,
                            Code = "ky"
                        },
                        new
                        {
                            Id = 116L,
                            Code = "lag"
                        },
                        new
                        {
                            Id = 117L,
                            Code = "lb"
                        },
                        new
                        {
                            Id = 118L,
                            Code = "lg"
                        },
                        new
                        {
                            Id = 119L,
                            Code = "lkt"
                        },
                        new
                        {
                            Id = 120L,
                            Code = "ln"
                        },
                        new
                        {
                            Id = 121L,
                            Code = "lo"
                        },
                        new
                        {
                            Id = 122L,
                            Code = "lrc"
                        },
                        new
                        {
                            Id = 123L,
                            Code = "lt"
                        },
                        new
                        {
                            Id = 124L,
                            Code = "lu"
                        },
                        new
                        {
                            Id = 125L,
                            Code = "luo"
                        },
                        new
                        {
                            Id = 126L,
                            Code = "luy"
                        },
                        new
                        {
                            Id = 127L,
                            Code = "lv"
                        },
                        new
                        {
                            Id = 128L,
                            Code = "mas"
                        },
                        new
                        {
                            Id = 129L,
                            Code = "mer"
                        },
                        new
                        {
                            Id = 130L,
                            Code = "mfe"
                        },
                        new
                        {
                            Id = 131L,
                            Code = "mg"
                        },
                        new
                        {
                            Id = 132L,
                            Code = "mgh"
                        },
                        new
                        {
                            Id = 133L,
                            Code = "mgo"
                        },
                        new
                        {
                            Id = 134L,
                            Code = "mi"
                        },
                        new
                        {
                            Id = 135L,
                            Code = "mk"
                        },
                        new
                        {
                            Id = 136L,
                            Code = "ml"
                        },
                        new
                        {
                            Id = 137L,
                            Code = "mn"
                        },
                        new
                        {
                            Id = 139L,
                            Code = "moh"
                        },
                        new
                        {
                            Id = 140L,
                            Code = "mr"
                        },
                        new
                        {
                            Id = 141L,
                            Code = "ms"
                        },
                        new
                        {
                            Id = 142L,
                            Code = "mt"
                        },
                        new
                        {
                            Id = 143L,
                            Code = "mua"
                        },
                        new
                        {
                            Id = 144L,
                            Code = "my"
                        },
                        new
                        {
                            Id = 145L,
                            Code = "mzn"
                        },
                        new
                        {
                            Id = 146L,
                            Code = "naq"
                        },
                        new
                        {
                            Id = 147L,
                            Code = "nb"
                        },
                        new
                        {
                            Id = 148L,
                            Code = "nd"
                        },
                        new
                        {
                            Id = 149L,
                            Code = "nds"
                        },
                        new
                        {
                            Id = 150L,
                            Code = "ne"
                        },
                        new
                        {
                            Id = 151L,
                            Code = "nl"
                        },
                        new
                        {
                            Id = 152L,
                            Code = "nmg"
                        },
                        new
                        {
                            Id = 153L,
                            Code = "nn"
                        },
                        new
                        {
                            Id = 154L,
                            Code = "nnh"
                        },
                        new
                        {
                            Id = 155L,
                            Code = "nqo"
                        },
                        new
                        {
                            Id = 156L,
                            Code = "nr"
                        },
                        new
                        {
                            Id = 157L,
                            Code = "nso"
                        },
                        new
                        {
                            Id = 158L,
                            Code = "nus"
                        },
                        new
                        {
                            Id = 159L,
                            Code = "nyn"
                        },
                        new
                        {
                            Id = 160L,
                            Code = "oc"
                        },
                        new
                        {
                            Id = 161L,
                            Code = "om"
                        },
                        new
                        {
                            Id = 162L,
                            Code = "or"
                        },
                        new
                        {
                            Id = 163L,
                            Code = "os"
                        },
                        new
                        {
                            Id = 164L,
                            Code = "pa"
                        },
                        new
                        {
                            Id = 167L,
                            Code = "pl"
                        },
                        new
                        {
                            Id = 168L,
                            Code = "prg"
                        },
                        new
                        {
                            Id = 169L,
                            Code = "ps"
                        },
                        new
                        {
                            Id = 170L,
                            Code = "pt"
                        },
                        new
                        {
                            Id = 171L,
                            Code = "qu"
                        },
                        new
                        {
                            Id = 172L,
                            Code = "quc"
                        },
                        new
                        {
                            Id = 173L,
                            Code = "rm"
                        },
                        new
                        {
                            Id = 174L,
                            Code = "rn"
                        },
                        new
                        {
                            Id = 175L,
                            Code = "ro"
                        },
                        new
                        {
                            Id = 176L,
                            Code = "rof"
                        },
                        new
                        {
                            Id = 177L,
                            Code = "ru"
                        },
                        new
                        {
                            Id = 178L,
                            Code = "rw"
                        },
                        new
                        {
                            Id = 179L,
                            Code = "rwk"
                        },
                        new
                        {
                            Id = 180L,
                            Code = "sa"
                        },
                        new
                        {
                            Id = 181L,
                            Code = "sah"
                        },
                        new
                        {
                            Id = 182L,
                            Code = "saq"
                        },
                        new
                        {
                            Id = 183L,
                            Code = "sbp"
                        },
                        new
                        {
                            Id = 184L,
                            Code = "sd"
                        },
                        new
                        {
                            Id = 185L,
                            Code = "se"
                        },
                        new
                        {
                            Id = 186L,
                            Code = "seh"
                        },
                        new
                        {
                            Id = 187L,
                            Code = "ses"
                        },
                        new
                        {
                            Id = 188L,
                            Code = "sg"
                        },
                        new
                        {
                            Id = 189L,
                            Code = "shi"
                        },
                        new
                        {
                            Id = 192L,
                            Code = "si"
                        },
                        new
                        {
                            Id = 193L,
                            Code = "sk"
                        },
                        new
                        {
                            Id = 194L,
                            Code = "sl"
                        },
                        new
                        {
                            Id = 195L,
                            Code = "sma"
                        },
                        new
                        {
                            Id = 196L,
                            Code = "smj"
                        },
                        new
                        {
                            Id = 197L,
                            Code = "smn"
                        },
                        new
                        {
                            Id = 198L,
                            Code = "sms"
                        },
                        new
                        {
                            Id = 199L,
                            Code = "sn"
                        },
                        new
                        {
                            Id = 200L,
                            Code = "so"
                        },
                        new
                        {
                            Id = 201L,
                            Code = "sq"
                        },
                        new
                        {
                            Id = 202L,
                            Code = "sr"
                        },
                        new
                        {
                            Id = 205L,
                            Code = "ss"
                        },
                        new
                        {
                            Id = 206L,
                            Code = "ssy"
                        },
                        new
                        {
                            Id = 207L,
                            Code = "st"
                        },
                        new
                        {
                            Id = 208L,
                            Code = "sv"
                        },
                        new
                        {
                            Id = 209L,
                            Code = "sw"
                        },
                        new
                        {
                            Id = 210L,
                            Code = "syr"
                        },
                        new
                        {
                            Id = 211L,
                            Code = "ta"
                        },
                        new
                        {
                            Id = 212L,
                            Code = "te"
                        },
                        new
                        {
                            Id = 213L,
                            Code = "teo"
                        },
                        new
                        {
                            Id = 214L,
                            Code = "tg"
                        },
                        new
                        {
                            Id = 215L,
                            Code = "th"
                        },
                        new
                        {
                            Id = 216L,
                            Code = "ti"
                        },
                        new
                        {
                            Id = 217L,
                            Code = "tig"
                        },
                        new
                        {
                            Id = 218L,
                            Code = "tk"
                        },
                        new
                        {
                            Id = 219L,
                            Code = "tn"
                        },
                        new
                        {
                            Id = 220L,
                            Code = "to"
                        },
                        new
                        {
                            Id = 221L,
                            Code = "tr"
                        },
                        new
                        {
                            Id = 222L,
                            Code = "ts"
                        },
                        new
                        {
                            Id = 223L,
                            Code = "tt"
                        },
                        new
                        {
                            Id = 224L,
                            Code = "twq"
                        },
                        new
                        {
                            Id = 225L,
                            Code = "tzm"
                        },
                        new
                        {
                            Id = 226L,
                            Code = "ug"
                        },
                        new
                        {
                            Id = 227L,
                            Code = "uk"
                        },
                        new
                        {
                            Id = 228L,
                            Code = "ur"
                        },
                        new
                        {
                            Id = 229L,
                            Code = "uz"
                        },
                        new
                        {
                            Id = 233L,
                            Code = "vai"
                        },
                        new
                        {
                            Id = 236L,
                            Code = "ve"
                        },
                        new
                        {
                            Id = 237L,
                            Code = "vi"
                        },
                        new
                        {
                            Id = 238L,
                            Code = "vo"
                        },
                        new
                        {
                            Id = 239L,
                            Code = "vun"
                        },
                        new
                        {
                            Id = 240L,
                            Code = "wae"
                        },
                        new
                        {
                            Id = 241L,
                            Code = "wal"
                        },
                        new
                        {
                            Id = 242L,
                            Code = "wo"
                        },
                        new
                        {
                            Id = 243L,
                            Code = "xh"
                        },
                        new
                        {
                            Id = 244L,
                            Code = "xog"
                        },
                        new
                        {
                            Id = 245L,
                            Code = "yav"
                        },
                        new
                        {
                            Id = 246L,
                            Code = "yi"
                        },
                        new
                        {
                            Id = 247L,
                            Code = "yo"
                        },
                        new
                        {
                            Id = 248L,
                            Code = "zgh"
                        },
                        new
                        {
                            Id = 249L,
                            Code = "zh"
                        },
                        new
                        {
                            Id = 252L,
                            Code = "zu"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Like", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("BookId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("likes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Paragraph", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChapterId")
                        .HasColumnType("bigint");

                    b.Property<long>("EndTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2083)
                        .HasColumnType("character varying(2083)");

                    b.Property<int>("ParagraphOrder")
                        .HasColumnType("integer");

                    b.Property<long>("StartTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.HasKey("Id");

                    b.HasAlternateKey("ChapterId", "ParagraphOrder");

                    b.ToTable("paragraphs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Story", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("CoverPath")
                        .HasMaxLength(2083)
                        .HasColumnType("character varying(2083)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("_createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LanguageId");

                    b.ToTable("books", null, t =>
                        {
                            t.Property("CreatedAt")
                                .HasColumnName("CreatedAt1");
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("Age")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(2083)
                        .HasColumnType("character varying(2083)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasAlternateKey("GoogleId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Audio", b =>
                {
                    b.HasOne("Domain.Entities.Chapter", "Chapter")
                        .WithOne("Audio")
                        .HasForeignKey("Domain.Entities.Audio", "ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Domain.Entities.Chapter", b =>
                {
                    b.HasOne("Domain.Entities.Story", "Book")
                        .WithMany("Chapters")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Domain.Entities.Like", b =>
                {
                    b.HasOne("Domain.Entities.Story", "Book")
                        .WithMany("Likes")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Paragraph", b =>
                {
                    b.HasOne("Domain.Entities.Chapter", "Chapter")
                        .WithMany("Paragraphs")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Domain.Entities.Story", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("Stories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Language", "Language")
                        .WithMany("Books")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Stories");
                });

            modelBuilder.Entity("Domain.Entities.Chapter", b =>
                {
                    b.Navigation("Audio");

                    b.Navigation("Paragraphs");
                });

            modelBuilder.Entity("Domain.Entities.Language", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Domain.Entities.Story", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
