// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.Contexts;

#nullable disable

namespace Kazka.Persistence.Migrations
{
    [DbContext(typeof(KazkaContext))]
    partial class KazkaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Audio", b =>
                {
                    b.Property<int>("ChapterId")
                        .HasColumnType("integer");

                    b.Property<string>("AudioPath")
                        .IsRequired()
                        .HasMaxLength(2083)
                        .HasColumnType("character varying(2083)");

                    b.HasKey("ChapterId");

                    b.ToTable("audios", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("Order")
                        .HasColumnType("smallint");

                    b.Property<int>("StoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.ToTable("chapters", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Code");

                    b.ToTable("languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "aa"
                        },
                        new
                        {
                            Id = 2,
                            Code = "af"
                        },
                        new
                        {
                            Id = 3,
                            Code = "agq"
                        },
                        new
                        {
                            Id = 4,
                            Code = "ak"
                        },
                        new
                        {
                            Id = 5,
                            Code = "am"
                        },
                        new
                        {
                            Id = 6,
                            Code = "ar"
                        },
                        new
                        {
                            Id = 7,
                            Code = "arn"
                        },
                        new
                        {
                            Id = 8,
                            Code = "as"
                        },
                        new
                        {
                            Id = 9,
                            Code = "asa"
                        },
                        new
                        {
                            Id = 10,
                            Code = "ast"
                        },
                        new
                        {
                            Id = 11,
                            Code = "az"
                        },
                        new
                        {
                            Id = 12,
                            Code = "ba"
                        },
                        new
                        {
                            Id = 13,
                            Code = "bas"
                        },
                        new
                        {
                            Id = 14,
                            Code = "be"
                        },
                        new
                        {
                            Id = 15,
                            Code = "bem"
                        },
                        new
                        {
                            Id = 16,
                            Code = "bez"
                        },
                        new
                        {
                            Id = 17,
                            Code = "bg"
                        },
                        new
                        {
                            Id = 18,
                            Code = "bm"
                        },
                        new
                        {
                            Id = 19,
                            Code = "bn"
                        },
                        new
                        {
                            Id = 20,
                            Code = "bo"
                        },
                        new
                        {
                            Id = 21,
                            Code = "br"
                        },
                        new
                        {
                            Id = 22,
                            Code = "brx"
                        },
                        new
                        {
                            Id = 23,
                            Code = "bs"
                        },
                        new
                        {
                            Id = 24,
                            Code = "byn"
                        },
                        new
                        {
                            Id = 25,
                            Code = "ca"
                        },
                        new
                        {
                            Id = 26,
                            Code = "ccp"
                        },
                        new
                        {
                            Id = 27,
                            Code = "ce"
                        },
                        new
                        {
                            Id = 28,
                            Code = "ceb"
                        },
                        new
                        {
                            Id = 29,
                            Code = "cgg"
                        },
                        new
                        {
                            Id = 30,
                            Code = "chr"
                        },
                        new
                        {
                            Id = 31,
                            Code = "ckb"
                        },
                        new
                        {
                            Id = 32,
                            Code = "co"
                        },
                        new
                        {
                            Id = 33,
                            Code = "cs"
                        },
                        new
                        {
                            Id = 34,
                            Code = "cu"
                        },
                        new
                        {
                            Id = 35,
                            Code = "cy"
                        },
                        new
                        {
                            Id = 36,
                            Code = "da"
                        },
                        new
                        {
                            Id = 37,
                            Code = "dav"
                        },
                        new
                        {
                            Id = 38,
                            Code = "de"
                        },
                        new
                        {
                            Id = 39,
                            Code = "dje"
                        },
                        new
                        {
                            Id = 40,
                            Code = "dsb"
                        },
                        new
                        {
                            Id = 41,
                            Code = "dua"
                        },
                        new
                        {
                            Id = 42,
                            Code = "dv"
                        },
                        new
                        {
                            Id = 43,
                            Code = "dyo"
                        },
                        new
                        {
                            Id = 44,
                            Code = "dz"
                        },
                        new
                        {
                            Id = 45,
                            Code = "ebu"
                        },
                        new
                        {
                            Id = 46,
                            Code = "ee"
                        },
                        new
                        {
                            Id = 47,
                            Code = "el"
                        },
                        new
                        {
                            Id = 48,
                            Code = "en"
                        },
                        new
                        {
                            Id = 49,
                            Code = "eo"
                        },
                        new
                        {
                            Id = 50,
                            Code = "es"
                        },
                        new
                        {
                            Id = 51,
                            Code = "et"
                        },
                        new
                        {
                            Id = 52,
                            Code = "eu"
                        },
                        new
                        {
                            Id = 53,
                            Code = "ewo"
                        },
                        new
                        {
                            Id = 54,
                            Code = "fa"
                        },
                        new
                        {
                            Id = 55,
                            Code = "ff"
                        },
                        new
                        {
                            Id = 56,
                            Code = "fi"
                        },
                        new
                        {
                            Id = 57,
                            Code = "fil"
                        },
                        new
                        {
                            Id = 58,
                            Code = "fo"
                        },
                        new
                        {
                            Id = 59,
                            Code = "fr"
                        },
                        new
                        {
                            Id = 60,
                            Code = "fur"
                        },
                        new
                        {
                            Id = 61,
                            Code = "fy"
                        },
                        new
                        {
                            Id = 62,
                            Code = "ga"
                        },
                        new
                        {
                            Id = 63,
                            Code = "gd"
                        },
                        new
                        {
                            Id = 64,
                            Code = "gl"
                        },
                        new
                        {
                            Id = 65,
                            Code = "gn"
                        },
                        new
                        {
                            Id = 66,
                            Code = "gsw"
                        },
                        new
                        {
                            Id = 67,
                            Code = "gu"
                        },
                        new
                        {
                            Id = 68,
                            Code = "guz"
                        },
                        new
                        {
                            Id = 69,
                            Code = "gv"
                        },
                        new
                        {
                            Id = 70,
                            Code = "ha"
                        },
                        new
                        {
                            Id = 71,
                            Code = "haw"
                        },
                        new
                        {
                            Id = 72,
                            Code = "he"
                        },
                        new
                        {
                            Id = 73,
                            Code = "hi"
                        },
                        new
                        {
                            Id = 74,
                            Code = "hr"
                        },
                        new
                        {
                            Id = 75,
                            Code = "hsb"
                        },
                        new
                        {
                            Id = 76,
                            Code = "hu"
                        },
                        new
                        {
                            Id = 77,
                            Code = "hy"
                        },
                        new
                        {
                            Id = 78,
                            Code = "ia"
                        },
                        new
                        {
                            Id = 79,
                            Code = "id"
                        },
                        new
                        {
                            Id = 80,
                            Code = "ig"
                        },
                        new
                        {
                            Id = 81,
                            Code = "ii"
                        },
                        new
                        {
                            Id = 82,
                            Code = "is"
                        },
                        new
                        {
                            Id = 83,
                            Code = "it"
                        },
                        new
                        {
                            Id = 84,
                            Code = "iu"
                        },
                        new
                        {
                            Id = 85,
                            Code = "ja"
                        },
                        new
                        {
                            Id = 86,
                            Code = "jgo"
                        },
                        new
                        {
                            Id = 87,
                            Code = "jmc"
                        },
                        new
                        {
                            Id = 88,
                            Code = "jv"
                        },
                        new
                        {
                            Id = 89,
                            Code = "ka"
                        },
                        new
                        {
                            Id = 90,
                            Code = "kab"
                        },
                        new
                        {
                            Id = 91,
                            Code = "kam"
                        },
                        new
                        {
                            Id = 92,
                            Code = "kde"
                        },
                        new
                        {
                            Id = 93,
                            Code = "kea"
                        },
                        new
                        {
                            Id = 94,
                            Code = "khq"
                        },
                        new
                        {
                            Id = 95,
                            Code = "ki"
                        },
                        new
                        {
                            Id = 96,
                            Code = "kk"
                        },
                        new
                        {
                            Id = 97,
                            Code = "kkj"
                        },
                        new
                        {
                            Id = 98,
                            Code = "kl"
                        },
                        new
                        {
                            Id = 99,
                            Code = "kln"
                        },
                        new
                        {
                            Id = 100,
                            Code = "km"
                        },
                        new
                        {
                            Id = 101,
                            Code = "kn"
                        },
                        new
                        {
                            Id = 102,
                            Code = "ko"
                        },
                        new
                        {
                            Id = 103,
                            Code = "kok"
                        },
                        new
                        {
                            Id = 104,
                            Code = "ks"
                        },
                        new
                        {
                            Id = 105,
                            Code = "ksb"
                        },
                        new
                        {
                            Id = 106,
                            Code = "ksf"
                        },
                        new
                        {
                            Id = 107,
                            Code = "ksh"
                        },
                        new
                        {
                            Id = 108,
                            Code = "kw"
                        },
                        new
                        {
                            Id = 109,
                            Code = "ky"
                        },
                        new
                        {
                            Id = 110,
                            Code = "lag"
                        },
                        new
                        {
                            Id = 111,
                            Code = "lb"
                        },
                        new
                        {
                            Id = 112,
                            Code = "lg"
                        },
                        new
                        {
                            Id = 113,
                            Code = "lkt"
                        },
                        new
                        {
                            Id = 114,
                            Code = "ln"
                        },
                        new
                        {
                            Id = 115,
                            Code = "lo"
                        },
                        new
                        {
                            Id = 116,
                            Code = "lrc"
                        },
                        new
                        {
                            Id = 117,
                            Code = "lt"
                        },
                        new
                        {
                            Id = 118,
                            Code = "lu"
                        },
                        new
                        {
                            Id = 119,
                            Code = "luo"
                        },
                        new
                        {
                            Id = 120,
                            Code = "luy"
                        },
                        new
                        {
                            Id = 121,
                            Code = "lv"
                        },
                        new
                        {
                            Id = 122,
                            Code = "mas"
                        },
                        new
                        {
                            Id = 123,
                            Code = "mer"
                        },
                        new
                        {
                            Id = 124,
                            Code = "mfe"
                        },
                        new
                        {
                            Id = 125,
                            Code = "mg"
                        },
                        new
                        {
                            Id = 126,
                            Code = "mgh"
                        },
                        new
                        {
                            Id = 127,
                            Code = "mgo"
                        },
                        new
                        {
                            Id = 128,
                            Code = "mi"
                        },
                        new
                        {
                            Id = 129,
                            Code = "mk"
                        },
                        new
                        {
                            Id = 130,
                            Code = "ml"
                        },
                        new
                        {
                            Id = 131,
                            Code = "mn"
                        },
                        new
                        {
                            Id = 132,
                            Code = "moh"
                        },
                        new
                        {
                            Id = 133,
                            Code = "mr"
                        },
                        new
                        {
                            Id = 134,
                            Code = "ms"
                        },
                        new
                        {
                            Id = 135,
                            Code = "mt"
                        },
                        new
                        {
                            Id = 136,
                            Code = "mua"
                        },
                        new
                        {
                            Id = 137,
                            Code = "my"
                        },
                        new
                        {
                            Id = 138,
                            Code = "mzn"
                        },
                        new
                        {
                            Id = 139,
                            Code = "naq"
                        },
                        new
                        {
                            Id = 140,
                            Code = "nb"
                        },
                        new
                        {
                            Id = 141,
                            Code = "nd"
                        },
                        new
                        {
                            Id = 142,
                            Code = "nds"
                        },
                        new
                        {
                            Id = 143,
                            Code = "ne"
                        },
                        new
                        {
                            Id = 144,
                            Code = "nl"
                        },
                        new
                        {
                            Id = 145,
                            Code = "nmg"
                        },
                        new
                        {
                            Id = 146,
                            Code = "nn"
                        },
                        new
                        {
                            Id = 147,
                            Code = "nnh"
                        },
                        new
                        {
                            Id = 148,
                            Code = "nqo"
                        },
                        new
                        {
                            Id = 149,
                            Code = "nr"
                        },
                        new
                        {
                            Id = 150,
                            Code = "nso"
                        },
                        new
                        {
                            Id = 151,
                            Code = "nus"
                        },
                        new
                        {
                            Id = 152,
                            Code = "nyn"
                        },
                        new
                        {
                            Id = 153,
                            Code = "oc"
                        },
                        new
                        {
                            Id = 154,
                            Code = "om"
                        },
                        new
                        {
                            Id = 155,
                            Code = "or"
                        },
                        new
                        {
                            Id = 156,
                            Code = "os"
                        },
                        new
                        {
                            Id = 157,
                            Code = "pa"
                        },
                        new
                        {
                            Id = 158,
                            Code = "pl"
                        },
                        new
                        {
                            Id = 159,
                            Code = "prg"
                        },
                        new
                        {
                            Id = 160,
                            Code = "ps"
                        },
                        new
                        {
                            Id = 161,
                            Code = "pt"
                        },
                        new
                        {
                            Id = 162,
                            Code = "qu"
                        },
                        new
                        {
                            Id = 163,
                            Code = "quc"
                        },
                        new
                        {
                            Id = 164,
                            Code = "rm"
                        },
                        new
                        {
                            Id = 165,
                            Code = "rn"
                        },
                        new
                        {
                            Id = 166,
                            Code = "ro"
                        },
                        new
                        {
                            Id = 167,
                            Code = "rof"
                        },
                        new
                        {
                            Id = 168,
                            Code = "ru"
                        },
                        new
                        {
                            Id = 169,
                            Code = "rw"
                        },
                        new
                        {
                            Id = 170,
                            Code = "rwk"
                        },
                        new
                        {
                            Id = 171,
                            Code = "sa"
                        },
                        new
                        {
                            Id = 172,
                            Code = "sah"
                        },
                        new
                        {
                            Id = 173,
                            Code = "saq"
                        },
                        new
                        {
                            Id = 174,
                            Code = "sbp"
                        },
                        new
                        {
                            Id = 175,
                            Code = "sd"
                        },
                        new
                        {
                            Id = 176,
                            Code = "se"
                        },
                        new
                        {
                            Id = 177,
                            Code = "seh"
                        },
                        new
                        {
                            Id = 178,
                            Code = "ses"
                        },
                        new
                        {
                            Id = 179,
                            Code = "sg"
                        },
                        new
                        {
                            Id = 180,
                            Code = "shi"
                        },
                        new
                        {
                            Id = 181,
                            Code = "si"
                        },
                        new
                        {
                            Id = 182,
                            Code = "sk"
                        },
                        new
                        {
                            Id = 183,
                            Code = "sl"
                        },
                        new
                        {
                            Id = 184,
                            Code = "sma"
                        },
                        new
                        {
                            Id = 185,
                            Code = "smj"
                        },
                        new
                        {
                            Id = 186,
                            Code = "smn"
                        },
                        new
                        {
                            Id = 187,
                            Code = "sms"
                        },
                        new
                        {
                            Id = 188,
                            Code = "sn"
                        },
                        new
                        {
                            Id = 189,
                            Code = "so"
                        },
                        new
                        {
                            Id = 190,
                            Code = "sq"
                        },
                        new
                        {
                            Id = 191,
                            Code = "sr"
                        },
                        new
                        {
                            Id = 192,
                            Code = "ss"
                        },
                        new
                        {
                            Id = 193,
                            Code = "ssy"
                        },
                        new
                        {
                            Id = 194,
                            Code = "st"
                        },
                        new
                        {
                            Id = 195,
                            Code = "sv"
                        },
                        new
                        {
                            Id = 196,
                            Code = "sw"
                        },
                        new
                        {
                            Id = 197,
                            Code = "syr"
                        },
                        new
                        {
                            Id = 198,
                            Code = "ta"
                        },
                        new
                        {
                            Id = 199,
                            Code = "te"
                        },
                        new
                        {
                            Id = 200,
                            Code = "teo"
                        },
                        new
                        {
                            Id = 201,
                            Code = "tg"
                        },
                        new
                        {
                            Id = 202,
                            Code = "th"
                        },
                        new
                        {
                            Id = 203,
                            Code = "ti"
                        },
                        new
                        {
                            Id = 204,
                            Code = "tig"
                        },
                        new
                        {
                            Id = 205,
                            Code = "tk"
                        },
                        new
                        {
                            Id = 206,
                            Code = "tn"
                        },
                        new
                        {
                            Id = 207,
                            Code = "to"
                        },
                        new
                        {
                            Id = 208,
                            Code = "tr"
                        },
                        new
                        {
                            Id = 209,
                            Code = "ts"
                        },
                        new
                        {
                            Id = 210,
                            Code = "tt"
                        },
                        new
                        {
                            Id = 211,
                            Code = "twq"
                        },
                        new
                        {
                            Id = 212,
                            Code = "tzm"
                        },
                        new
                        {
                            Id = 213,
                            Code = "ug"
                        },
                        new
                        {
                            Id = 214,
                            Code = "uk"
                        },
                        new
                        {
                            Id = 215,
                            Code = "ur"
                        },
                        new
                        {
                            Id = 216,
                            Code = "uz"
                        },
                        new
                        {
                            Id = 217,
                            Code = "vai"
                        },
                        new
                        {
                            Id = 218,
                            Code = "ve"
                        },
                        new
                        {
                            Id = 219,
                            Code = "vi"
                        },
                        new
                        {
                            Id = 220,
                            Code = "vo"
                        },
                        new
                        {
                            Id = 221,
                            Code = "vun"
                        },
                        new
                        {
                            Id = 222,
                            Code = "wae"
                        },
                        new
                        {
                            Id = 223,
                            Code = "wal"
                        },
                        new
                        {
                            Id = 224,
                            Code = "wo"
                        },
                        new
                        {
                            Id = 225,
                            Code = "xh"
                        },
                        new
                        {
                            Id = 226,
                            Code = "xog"
                        },
                        new
                        {
                            Id = 227,
                            Code = "yav"
                        },
                        new
                        {
                            Id = 228,
                            Code = "yi"
                        },
                        new
                        {
                            Id = 229,
                            Code = "yo"
                        },
                        new
                        {
                            Id = 230,
                            Code = "zgh"
                        },
                        new
                        {
                            Id = 231,
                            Code = "zh"
                        },
                        new
                        {
                            Id = 232,
                            Code = "zu"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Like", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("likes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Paragraph", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("integer");

                    b.Property<int>("EndTimeMs")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2083)
                        .HasColumnType("character varying(2083)");

                    b.Property<int>("ParagraphOrder")
                        .HasColumnType("integer");

                    b.Property<int>("StartTimeMs")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.HasKey("Id");

                    b.HasAlternateKey("ChapterId", "ParagraphOrder");

                    b.ToTable("paragraphs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverPath")
                        .HasMaxLength(2083)
                        .HasColumnType("character varying(2083)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("_createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<byte?>("Age")
                        .HasColumnType("smallint");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(2083)
                        .HasColumnType("character varying(2083)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("_createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasAlternateKey("GoogleId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Kazka.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashedToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("_createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Kazka.Core.Entities.StoryCategory", b =>
                {
                    b.Property<int>("StoryId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.HasKey("StoryId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("story_categories", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Audio", b =>
                {
                    b.HasOne("Domain.Entities.Chapter", "Chapter")
                        .WithOne("Audio")
                        .HasForeignKey("Domain.Entities.Audio", "ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Domain.Entities.Chapter", b =>
                {
                    b.HasOne("Domain.Entities.Story", "Story")
                        .WithMany("Chapters")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Domain.Entities.Like", b =>
                {
                    b.HasOne("Domain.Entities.Story", "Book")
                        .WithMany("Likes")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Paragraph", b =>
                {
                    b.HasOne("Domain.Entities.Chapter", "Chapter")
                        .WithMany("Paragraphs")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Domain.Entities.Story", b =>
                {
                    b.HasOne("Domain.Entities.Language", "Language")
                        .WithMany("Stories")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Kazka.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kazka.Core.Entities.StoryCategory", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("StoryCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Story", "Story")
                        .WithMany("StoryCategories")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("StoryCategories");
                });

            modelBuilder.Entity("Domain.Entities.Chapter", b =>
                {
                    b.Navigation("Audio");

                    b.Navigation("Paragraphs");
                });

            modelBuilder.Entity("Domain.Entities.Language", b =>
                {
                    b.Navigation("Stories");
                });

            modelBuilder.Entity("Domain.Entities.Story", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Likes");

                    b.Navigation("StoryCategories");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
