// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.Contexts;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(KazkaDbContext))]
    [Migration("20251015181816_Migration2")]
    partial class Migration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Audio", b =>
                {
                    b.Property<int>("ChapterId")
                        .HasColumnType("integer");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(2083)
                        .HasColumnType("character varying(2083)");

                    b.HasKey("ChapterId");

                    b.ToTable("audios", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Domain.Entities.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<short>("Number")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("chapters", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Code");

                    b.ToTable("languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "iv",
                            Name = "Invariant Language (Invariant Country)"
                        },
                        new
                        {
                            Id = 2,
                            Code = "aa",
                            Name = "Afar"
                        },
                        new
                        {
                            Id = 3,
                            Code = "af",
                            Name = "Afrikaans"
                        },
                        new
                        {
                            Id = 4,
                            Code = "ak",
                            Name = "Akan"
                        },
                        new
                        {
                            Id = 5,
                            Code = "am",
                            Name = "Amharic"
                        },
                        new
                        {
                            Id = 6,
                            Code = "ar",
                            Name = "Arabic"
                        },
                        new
                        {
                            Id = 7,
                            Code = "as",
                            Name = "Assamese"
                        },
                        new
                        {
                            Id = 8,
                            Code = "az",
                            Name = "Azerbaijani"
                        },
                        new
                        {
                            Id = 11,
                            Code = "ba",
                            Name = "Bashkir"
                        },
                        new
                        {
                            Id = 12,
                            Code = "be",
                            Name = "Belarusian"
                        },
                        new
                        {
                            Id = 13,
                            Code = "bg",
                            Name = "Bulgarian"
                        },
                        new
                        {
                            Id = 14,
                            Code = "bm",
                            Name = "Bamanankan"
                        },
                        new
                        {
                            Id = 15,
                            Code = "bn",
                            Name = "Bangla"
                        },
                        new
                        {
                            Id = 16,
                            Code = "bo",
                            Name = "Tibetan"
                        },
                        new
                        {
                            Id = 17,
                            Code = "br",
                            Name = "Breton"
                        },
                        new
                        {
                            Id = 18,
                            Code = "bs",
                            Name = "Bosnian"
                        },
                        new
                        {
                            Id = 21,
                            Code = "ca",
                            Name = "Catalan"
                        },
                        new
                        {
                            Id = 22,
                            Code = "ce",
                            Name = "Chechen"
                        },
                        new
                        {
                            Id = 23,
                            Code = "co",
                            Name = "Corsican"
                        },
                        new
                        {
                            Id = 24,
                            Code = "cs",
                            Name = "Czech"
                        },
                        new
                        {
                            Id = 25,
                            Code = "cu",
                            Name = "Church Slavic"
                        },
                        new
                        {
                            Id = 26,
                            Code = "cy",
                            Name = "Welsh"
                        },
                        new
                        {
                            Id = 27,
                            Code = "da",
                            Name = "Danish"
                        },
                        new
                        {
                            Id = 28,
                            Code = "de",
                            Name = "German"
                        },
                        new
                        {
                            Id = 29,
                            Code = "dv",
                            Name = "Divehi"
                        },
                        new
                        {
                            Id = 30,
                            Code = "dz",
                            Name = "Dzongkha"
                        },
                        new
                        {
                            Id = 31,
                            Code = "ee",
                            Name = "Ewe"
                        },
                        new
                        {
                            Id = 32,
                            Code = "el",
                            Name = "Greek"
                        },
                        new
                        {
                            Id = 33,
                            Code = "en",
                            Name = "English"
                        },
                        new
                        {
                            Id = 34,
                            Code = "eo",
                            Name = "Esperanto"
                        },
                        new
                        {
                            Id = 35,
                            Code = "es",
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = 36,
                            Code = "et",
                            Name = "Estonian"
                        },
                        new
                        {
                            Id = 37,
                            Code = "eu",
                            Name = "Basque"
                        },
                        new
                        {
                            Id = 38,
                            Code = "fa",
                            Name = "Persian"
                        },
                        new
                        {
                            Id = 39,
                            Code = "ff",
                            Name = "Fulah"
                        },
                        new
                        {
                            Id = 41,
                            Code = "fi",
                            Name = "Finnish"
                        },
                        new
                        {
                            Id = 42,
                            Code = "fo",
                            Name = "Faroese"
                        },
                        new
                        {
                            Id = 43,
                            Code = "fr",
                            Name = "French"
                        },
                        new
                        {
                            Id = 44,
                            Code = "fy",
                            Name = "Western Frisian"
                        },
                        new
                        {
                            Id = 45,
                            Code = "ga",
                            Name = "Irish"
                        },
                        new
                        {
                            Id = 46,
                            Code = "gd",
                            Name = "Scottish Gaelic"
                        },
                        new
                        {
                            Id = 47,
                            Code = "gl",
                            Name = "Galician"
                        },
                        new
                        {
                            Id = 48,
                            Code = "gn",
                            Name = "Guarani"
                        },
                        new
                        {
                            Id = 49,
                            Code = "gu",
                            Name = "Gujarati"
                        },
                        new
                        {
                            Id = 50,
                            Code = "gv",
                            Name = "Manx"
                        },
                        new
                        {
                            Id = 51,
                            Code = "ha",
                            Name = "Hausa"
                        },
                        new
                        {
                            Id = 52,
                            Code = "he",
                            Name = "Hebrew"
                        },
                        new
                        {
                            Id = 53,
                            Code = "hi",
                            Name = "Hindi"
                        },
                        new
                        {
                            Id = 54,
                            Code = "hr",
                            Name = "Croatian"
                        },
                        new
                        {
                            Id = 55,
                            Code = "hu",
                            Name = "Hungarian"
                        },
                        new
                        {
                            Id = 56,
                            Code = "hy",
                            Name = "Armenian"
                        },
                        new
                        {
                            Id = 57,
                            Code = "ia",
                            Name = "Interlingua"
                        },
                        new
                        {
                            Id = 58,
                            Code = "id",
                            Name = "Indonesian"
                        },
                        new
                        {
                            Id = 59,
                            Code = "ig",
                            Name = "Igbo"
                        },
                        new
                        {
                            Id = 60,
                            Code = "ii",
                            Name = "Yi"
                        },
                        new
                        {
                            Id = 61,
                            Code = "is",
                            Name = "Icelandic"
                        },
                        new
                        {
                            Id = 62,
                            Code = "it",
                            Name = "Italian"
                        },
                        new
                        {
                            Id = 63,
                            Code = "iu",
                            Name = "Inuktitut"
                        },
                        new
                        {
                            Id = 65,
                            Code = "ja",
                            Name = "Japanese"
                        },
                        new
                        {
                            Id = 66,
                            Code = "jv",
                            Name = "Javanese"
                        },
                        new
                        {
                            Id = 67,
                            Code = "ka",
                            Name = "Georgian"
                        },
                        new
                        {
                            Id = 68,
                            Code = "ki",
                            Name = "Kikuyu"
                        },
                        new
                        {
                            Id = 69,
                            Code = "kk",
                            Name = "Kazakh"
                        },
                        new
                        {
                            Id = 70,
                            Code = "kl",
                            Name = "Kalaallisut"
                        },
                        new
                        {
                            Id = 71,
                            Code = "km",
                            Name = "Khmer"
                        },
                        new
                        {
                            Id = 72,
                            Code = "kn",
                            Name = "Kannada"
                        },
                        new
                        {
                            Id = 73,
                            Code = "ko",
                            Name = "Korean"
                        },
                        new
                        {
                            Id = 74,
                            Code = "ks",
                            Name = "Kashmiri"
                        },
                        new
                        {
                            Id = 75,
                            Code = "kw",
                            Name = "Cornish"
                        },
                        new
                        {
                            Id = 76,
                            Code = "ky",
                            Name = "Kyrgyz"
                        },
                        new
                        {
                            Id = 77,
                            Code = "lb",
                            Name = "Luxembourgish"
                        },
                        new
                        {
                            Id = 78,
                            Code = "lg",
                            Name = "Ganda"
                        },
                        new
                        {
                            Id = 79,
                            Code = "ln",
                            Name = "Lingala"
                        },
                        new
                        {
                            Id = 80,
                            Code = "lo",
                            Name = "Lao"
                        },
                        new
                        {
                            Id = 81,
                            Code = "lt",
                            Name = "Lithuanian"
                        },
                        new
                        {
                            Id = 82,
                            Code = "lu",
                            Name = "Luba-Katanga"
                        },
                        new
                        {
                            Id = 83,
                            Code = "lv",
                            Name = "Latvian"
                        },
                        new
                        {
                            Id = 84,
                            Code = "mg",
                            Name = "Malagasy"
                        },
                        new
                        {
                            Id = 85,
                            Code = "mi",
                            Name = "Maori"
                        },
                        new
                        {
                            Id = 86,
                            Code = "mk",
                            Name = "Macedonian"
                        },
                        new
                        {
                            Id = 87,
                            Code = "ml",
                            Name = "Malayalam"
                        },
                        new
                        {
                            Id = 88,
                            Code = "mn",
                            Name = "Mongolian"
                        },
                        new
                        {
                            Id = 90,
                            Code = "mr",
                            Name = "Marathi"
                        },
                        new
                        {
                            Id = 91,
                            Code = "ms",
                            Name = "Malay"
                        },
                        new
                        {
                            Id = 92,
                            Code = "mt",
                            Name = "Maltese"
                        },
                        new
                        {
                            Id = 93,
                            Code = "my",
                            Name = "Burmese"
                        },
                        new
                        {
                            Id = 94,
                            Code = "nb",
                            Name = "Norwegian Bokmål"
                        },
                        new
                        {
                            Id = 95,
                            Code = "nd",
                            Name = "North Ndebele"
                        },
                        new
                        {
                            Id = 96,
                            Code = "ne",
                            Name = "Nepali"
                        },
                        new
                        {
                            Id = 97,
                            Code = "nl",
                            Name = "Dutch"
                        },
                        new
                        {
                            Id = 98,
                            Code = "nn",
                            Name = "Norwegian Nynorsk"
                        },
                        new
                        {
                            Id = 99,
                            Code = "nr",
                            Name = "South Ndebele"
                        },
                        new
                        {
                            Id = 100,
                            Code = "oc",
                            Name = "Occitan"
                        },
                        new
                        {
                            Id = 101,
                            Code = "om",
                            Name = "Oromo"
                        },
                        new
                        {
                            Id = 102,
                            Code = "or",
                            Name = "Odia"
                        },
                        new
                        {
                            Id = 103,
                            Code = "os",
                            Name = "Ossetic"
                        },
                        new
                        {
                            Id = 104,
                            Code = "pa",
                            Name = "Punjabi"
                        },
                        new
                        {
                            Id = 107,
                            Code = "pl",
                            Name = "Polish"
                        },
                        new
                        {
                            Id = 108,
                            Code = "ps",
                            Name = "Pashto"
                        },
                        new
                        {
                            Id = 109,
                            Code = "pt",
                            Name = "Portuguese"
                        },
                        new
                        {
                            Id = 110,
                            Code = "qu",
                            Name = "Quechua"
                        },
                        new
                        {
                            Id = 111,
                            Code = "rm",
                            Name = "Romansh"
                        },
                        new
                        {
                            Id = 112,
                            Code = "rn",
                            Name = "Rundi"
                        },
                        new
                        {
                            Id = 113,
                            Code = "ro",
                            Name = "Romanian"
                        },
                        new
                        {
                            Id = 114,
                            Code = "ru",
                            Name = "Russian"
                        },
                        new
                        {
                            Id = 115,
                            Code = "rw",
                            Name = "Kinyarwanda"
                        },
                        new
                        {
                            Id = 116,
                            Code = "sa",
                            Name = "Sanskrit"
                        },
                        new
                        {
                            Id = 117,
                            Code = "sd",
                            Name = "Sindhi"
                        },
                        new
                        {
                            Id = 118,
                            Code = "se",
                            Name = "Northern Sami"
                        },
                        new
                        {
                            Id = 119,
                            Code = "sg",
                            Name = "Sango"
                        },
                        new
                        {
                            Id = 120,
                            Code = "si",
                            Name = "Sinhala"
                        },
                        new
                        {
                            Id = 121,
                            Code = "sk",
                            Name = "Slovak"
                        },
                        new
                        {
                            Id = 122,
                            Code = "sl",
                            Name = "Slovenian"
                        },
                        new
                        {
                            Id = 123,
                            Code = "sn",
                            Name = "Shona"
                        },
                        new
                        {
                            Id = 124,
                            Code = "so",
                            Name = "Somali"
                        },
                        new
                        {
                            Id = 125,
                            Code = "sq",
                            Name = "Albanian"
                        },
                        new
                        {
                            Id = 126,
                            Code = "sr",
                            Name = "Serbian"
                        },
                        new
                        {
                            Id = 129,
                            Code = "ss",
                            Name = "siSwati"
                        },
                        new
                        {
                            Id = 130,
                            Code = "st",
                            Name = "Sesotho"
                        },
                        new
                        {
                            Id = 131,
                            Code = "sv",
                            Name = "Swedish"
                        },
                        new
                        {
                            Id = 132,
                            Code = "sw",
                            Name = "Kiswahili"
                        },
                        new
                        {
                            Id = 133,
                            Code = "ta",
                            Name = "Tamil"
                        },
                        new
                        {
                            Id = 134,
                            Code = "te",
                            Name = "Telugu"
                        },
                        new
                        {
                            Id = 135,
                            Code = "tg",
                            Name = "Tajik"
                        },
                        new
                        {
                            Id = 136,
                            Code = "th",
                            Name = "Thai"
                        },
                        new
                        {
                            Id = 137,
                            Code = "ti",
                            Name = "Tigrinya"
                        },
                        new
                        {
                            Id = 138,
                            Code = "tk",
                            Name = "Turkmen"
                        },
                        new
                        {
                            Id = 139,
                            Code = "tn",
                            Name = "Setswana"
                        },
                        new
                        {
                            Id = 140,
                            Code = "to",
                            Name = "Tongan"
                        },
                        new
                        {
                            Id = 141,
                            Code = "tr",
                            Name = "Turkish"
                        },
                        new
                        {
                            Id = 142,
                            Code = "ts",
                            Name = "Xitsonga"
                        },
                        new
                        {
                            Id = 143,
                            Code = "tt",
                            Name = "Tatar"
                        },
                        new
                        {
                            Id = 144,
                            Code = "ug",
                            Name = "Uyghur"
                        },
                        new
                        {
                            Id = 145,
                            Code = "uk",
                            Name = "Ukrainian"
                        },
                        new
                        {
                            Id = 146,
                            Code = "ur",
                            Name = "Urdu"
                        },
                        new
                        {
                            Id = 147,
                            Code = "uz",
                            Name = "Uzbek"
                        },
                        new
                        {
                            Id = 151,
                            Code = "ve",
                            Name = "Venda"
                        },
                        new
                        {
                            Id = 152,
                            Code = "vi",
                            Name = "Vietnamese"
                        },
                        new
                        {
                            Id = 153,
                            Code = "vo",
                            Name = "Volapük"
                        },
                        new
                        {
                            Id = 154,
                            Code = "wo",
                            Name = "Wolof"
                        },
                        new
                        {
                            Id = 155,
                            Code = "xh",
                            Name = "isiXhosa"
                        },
                        new
                        {
                            Id = 156,
                            Code = "yi",
                            Name = "Yiddish"
                        },
                        new
                        {
                            Id = 157,
                            Code = "yo",
                            Name = "Yoruba"
                        },
                        new
                        {
                            Id = 158,
                            Code = "zh",
                            Name = "Chinese"
                        },
                        new
                        {
                            Id = 161,
                            Code = "zu",
                            Name = "isiZulu"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Like", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("likes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Paragraph", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("integer");

                    b.Property<int>("EndTimeMs")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2083)
                        .HasColumnType("character varying(2083)");

                    b.Property<short>("OrderNumber")
                        .HasColumnType("smallint");

                    b.Property<int>("StartTimeMs")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.HasKey("Id");

                    b.HasAlternateKey("ChapterId", "OrderNumber");

                    b.ToTable("paragraphs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("CoverPath")
                        .HasMaxLength(2083)
                        .HasColumnType("character varying(2083)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LanguageId");

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(2083)
                        .HasColumnType("character varying(2083)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasAlternateKey("GoogleId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Audio", b =>
                {
                    b.HasOne("Domain.Entities.Chapter", "Chapter")
                        .WithOne("Audio")
                        .HasForeignKey("Domain.Entities.Audio", "ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Domain.Entities.Chapter", b =>
                {
                    b.HasOne("Domain.Entities.Story", "Book")
                        .WithMany("Chapters")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Domain.Entities.Like", b =>
                {
                    b.HasOne("Domain.Entities.Story", "Book")
                        .WithMany("Likes")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Paragraph", b =>
                {
                    b.HasOne("Domain.Entities.Chapter", "Chapter")
                        .WithMany("Paragraphs")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Domain.Entities.Story", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("Stories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Language", "Language")
                        .WithMany("Books")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Stories");
                });

            modelBuilder.Entity("Domain.Entities.Chapter", b =>
                {
                    b.Navigation("Audio");

                    b.Navigation("Paragraphs");
                });

            modelBuilder.Entity("Domain.Entities.Language", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Domain.Entities.Story", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
